import { TypedQueryDocumentNode } from "graphql";
import { gql } from "graphql-request";

const ALL_COUNTRIES_QUERY = gql`
  {
    countries {
      code
      name
    }
  }
`;

// this would be autogenerated in a real-life project
type AllCountriesQueryResult = {
  countries: Array<{ code: string; name: string }>;
};
// this would be autogenerated in a real-life project
type AllCountriesVariables = null;
// this would be autogenerated in a real-life project
export const typedAllCountriesQuery =
  ALL_COUNTRIES_QUERY as any as TypedQueryDocumentNode<
    AllCountriesQueryResult,
    AllCountriesVariables
  >;
